version: '3'
services:
  devbox:
    build:
      context: ./dockerfile-cont
      dockerfile: DevBox.DockerFile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/html/app
  devmysql:
    build:
      context: ./dockerfile-cont
      dockerfile: MySQLDev.DockerFile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'VirtualAppliance0952'
      MYSQL_ALLOW_EMPTY_PASSWORD : 'no'
      MYSQL_USER: test1234
      MYSQL_PASSWORD: test1234
    restart: always
    volumes:
            #- container-volume:/var/lib/mysql
            - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql        
